// Generated by ts-to-zod

import { schema } from '../triplit/triplitTestSchema.js'
import type { Entity } from '@triplit/client'
//
export type SessionType = Entity<typeof schema, 'plain'>
// export const sessionTypeSchema = entitySchema
